---
abstract: 'control OBS via the WebSocket plugin'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Protocol-OBSRemote
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Filter::signatures: '0.09'
  Future: '0'
  Future::Mojo: '0'
  Getopt::Long: '0'
  Moo: '2'
  Moo::Role: '2'
  POSIX: '0'
  Pod::Usage: '0'
  perl: '5.012'
resources:
  bugtracker: https://github.com/Corion/Net-Protocol-OBSRemote/issues
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/Net-Protocol-OBSRemote.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
